### PR TITLE
Feature/vimeo api module

### PR DESCRIPTION
**Pull request by dryldionisio**
This change is [Reviewable](https://reviewable.io/reviews/jimmybatuhan/riival/21)

### CODE REVIEW

**Review by jimmybatuhan — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/jimmybatuhan/riival/21)* status: 1 of 9 files reviewed, 8 unresolved discussions (waiting on @dryldionisio and @jimmybatuhan)

___
*[composer.json, line 41 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/21#-MN8Xn-C8tReanVLCf9q:-MN8Xn-C8tReanVLCf9r:bdz662y) ([raw file](https://github.com/jimmybatuhan/riival/blob/12e2a5bdec3da5ee4884205a9c65ee74f1c5e6d6/composer.json#L41)):*
> ```
>  "Modules\\": "app/Modules/"
> ```
this will load the files everytime, which is already included in the `App\\`
___
*[app/Modules/Vimeo/config.php, line 6 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/21#-MN8Y0V8962WJsPaUQBb:-MN8Y0V8962WJsPaUQBc:b-10obsc) ([raw file](https://github.com/jimmybatuhan/riival/blob/12e2a5bdec3da5ee4884205a9c65ee74f1c5e6d6/app/Modules/Vimeo/config.php#L6)):*
> ```
>     'client_id' => env('VIMEO_CLIENT_ID', null),
>     'client_secret' => env('VIMEO_CLIENT_SECRET', null),
>     'access_token' => env('VIMEO_ACESS_TOKEN', null),
> ```
just add these in the *app.php*
___
*[app/Modules/Vimeo/Models/Video.php, line 14 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/21#-MN3PuEt8QtUmccz9Zb0:-MN3PuEu3PifWQ3K79_a:bp0n5qe) ([raw file](https://github.com/jimmybatuhan/riival/blob/12e2a5bdec3da5ee4884205a9c65ee74f1c5e6d6/app/Modules/Vimeo/Models/Video.php#L14)):*
> ```PHP
>     protected $guarded = ['id', 'created_at', 'update_at', 'deleted_at'];
> 
>     public function upload($filename, $title, $attr = [])
> ```

typehint
___
*[app/Modules/Vimeo/Models/Video.php, line 14 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/21#-MN8YBjy-rvSqHBGMzGw:-MN8YBjy-rvSqHBGMzGx:bpsr8xx) ([raw file](https://github.com/jimmybatuhan/riival/blob/12e2a5bdec3da5ee4884205a9c65ee74f1c5e6d6/app/Modules/Vimeo/Models/Video.php#L14)):*
> ```PHP
>     protected $guarded = ['id', 'created_at', 'update_at', 'deleted_at'];
> 
>     public function upload($filename, $title, $attr = [])
> ```

return type
___
*[app/Modules/Vimeo/Models/Video.php, line 25 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/21#-MN8YGjgEa0ExclhPPJP:-MN8YGjgEa0ExclhPPJQ:bbj1h53) ([raw file](https://github.com/jimmybatuhan/riival/blob/12e2a5bdec3da5ee4884205a9c65ee74f1c5e6d6/app/Modules/Vimeo/Models/Video.php#L25)):*
> ```PHP
>     }
> 
>     public function get($id)
> ```

typehint and return type
___
*[app/Modules/Vimeo/Models/Video.php, line 27 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/21#-MN8YFBf2TxCuBtupirg:-MN8YFBf2TxCuBtupirh:bh3o6fy) ([raw file](https://github.com/jimmybatuhan/riival/blob/12e2a5bdec3da5ee4884205a9c65ee74f1c5e6d6/app/Modules/Vimeo/Models/Video.php#L27)):*
> ```PHP
>     public function get($id)
>     {
> ```

remove empty line
___
*[app/Modules/Vimeo/migrations/2020_11_10_070645_create_videos_table.php, line 9 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/21#-MN8YKxGAa-3LUcrHD8W:-MN8YKxGAa-3LUcrHD8X:b9xlo3k) ([raw file](https://github.com/jimmybatuhan/riival/blob/12e2a5bdec3da5ee4884205a9c65ee74f1c5e6d6/app/Modules/Vimeo/migrations/2020_11_10_070645_create_videos_table.php#L9)):*
> ```PHP
> use Illuminate\Support\Facades\Schema;
> 
> class CreateVideosTable extends Migration
> ```

just add in the regular migration folder
___
*[config/app.php, line 231 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/21#-MN8YQZS6cilojwU3aOv:-MN8YQZS6cilojwU3aOw:b-277b5i) ([raw file](https://github.com/jimmybatuhan/riival/blob/12e2a5bdec3da5ee4884205a9c65ee74f1c5e6d6/config/app.php#L231)):*
> ```PHP
>         'Validator' => Illuminate\Support\Facades\Validator::class,
>         'View' => Illuminate\Support\Facades\View::class,
>         'Vimeo' =>  Modules\Vimeo\Facades\Vimeo::class
> ```

always add comma

**Comment by dryldionisio** [comment]
___
*[composer.json, line 41 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/21#-MN8Xn-C8tReanVLCf9q:-MNLtdRUDCibg0vhMltT:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/12e2a5bdec3da5ee4884205a9c65ee74f1c5e6d6/composer.json#L41)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

> ```
>  "Modules\\": "app/Modules/"
> ```
this will load the files everytime, which is already included in the `App\\`
</blockquote></details>

Done.

**Comment by dryldionisio** [comment]
___
*[app/Modules/Vimeo/config.php, line 6 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/21#-MN8Y0V8962WJsPaUQBb:-MNLtgNn4ypEZZ_nAiBn:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/12e2a5bdec3da5ee4884205a9c65ee74f1c5e6d6/app/Modules/Vimeo/config.php#L6)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

> ```
>     'client_id' => env('VIMEO_CLIENT_ID', null),
>     'client_secret' => env('VIMEO_CLIENT_SECRET', null),
>     'access_token' => env('VIMEO_ACESS_TOKEN', null),
> ```
just add these in the *app.php*
</blockquote></details>

Done.

**Comment by dryldionisio** [comment]
___
*[app/Modules/Vimeo/Models/Video.php, line 14 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/21#-MN3PuEt8QtUmccz9Zb0:-MNLtt3Y2A43mR9Rikhk:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/12e2a5bdec3da5ee4884205a9c65ee74f1c5e6d6/app/Modules/Vimeo/Models/Video.php#L14)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

typehint
</blockquote></details>

Done.

**Comment by dryldionisio** [comment]
___
*[app/Modules/Vimeo/Models/Video.php, line 14 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/21#-MN8YBjy-rvSqHBGMzGw:-MNLtvSpCg40jjIyEVMt:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/12e2a5bdec3da5ee4884205a9c65ee74f1c5e6d6/app/Modules/Vimeo/Models/Video.php#L14)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

return type
</blockquote></details>

Done.

**Comment by dryldionisio** [comment]
___
*[app/Modules/Vimeo/Models/Video.php, line 25 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/21#-MN8YGjgEa0ExclhPPJP:-MNLtyyE6zSBRlOzMhuC:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/12e2a5bdec3da5ee4884205a9c65ee74f1c5e6d6/app/Modules/Vimeo/Models/Video.php#L25)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

typehint and return type
</blockquote></details>

Done.

**Comment by dryldionisio** [comment]
___
*[app/Modules/Vimeo/Models/Video.php, line 27 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/21#-MN8YFBf2TxCuBtupirg:-MNLu14UEPx33BkpHMTr:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/12e2a5bdec3da5ee4884205a9c65ee74f1c5e6d6/app/Modules/Vimeo/Models/Video.php#L27)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

remove empty line
</blockquote></details>

Done.

**Comment by dryldionisio** [comment]
___
*[app/Modules/Vimeo/migrations/2020_11_10_070645_create_videos_table.php, line 9 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/21#-MN8YKxGAa-3LUcrHD8W:-MNLu5OT-z0cRttE3Ees:b-a4rirf) ([raw file](https://github.com/jimmybatuhan/riival/blob/12e2a5bdec3da5ee4884205a9c65ee74f1c5e6d6/app/Modules/Vimeo/migrations/2020_11_10_070645_create_videos_table.php#L9)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

just add in the regular migration folder
</blockquote></details>

Done. remove as its not needed

**Comment by dryldionisio** [comment]
___
*[config/app.php, line 231 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/21#-MN8YQZS6cilojwU3aOv:-MNLu9l2BCHN8Z08uavZ:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/12e2a5bdec3da5ee4884205a9c65ee74f1c5e6d6/config/app.php#L231)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

always add comma
</blockquote></details>

Done.

**Review by jimmybatuhan — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, 7 of 7 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 5 of 5 files at r7, 6 of 8 files at r8.
> *[Reviewable](https://reviewable.io/reviews/jimmybatuhan/riival/21)* status: 7 of 9 files reviewed, 8 unresolved discussions (waiting on @dryldionisio and @jimmybatuhan)

___
*[app/Http/Controllers/LessonController.php, line 5 at r8](https://reviewable.io/reviews/jimmybatuhan/riival/21#-MNpOsxWApspChMMn9Hh:-MNpOsxWApspChMMn9Hi:b-c42cp1) ([raw file](https://github.com/jimmybatuhan/riival/blob/190cc69a0d9ebbde2199efbc57c525186a98ecc7/app/Http/Controllers/LessonController.php#L5)):*
> ```PHP
> namespace App\Http\Controllers;
> 
> use Illuminate\Http\Request;
> ```

Sort ascending
___
*[app/Http/Controllers/LessonController.php, line 6 at r8](https://reviewable.io/reviews/jimmybatuhan/riival/21#-MNpNhCD4QKo59b9N1ew:-MNpNhCD4QKo59b9N1ex:bh3o6fy) ([raw file](https://github.com/jimmybatuhan/riival/blob/190cc69a0d9ebbde2199efbc57c525186a98ecc7/app/Http/Controllers/LessonController.php#L6)):*
> ```PHP
> 
> use Illuminate\Http\Request;
> ```

remove empty line
___
*[app/Http/Controllers/LessonController.php, line 25 at r8](https://reviewable.io/reviews/jimmybatuhan/riival/21#-MNpNw7Q44BKs-LKBz0U:-MNpNw7Q44BKs-LKBz0V:b-sfihw7) ([raw file](https://github.com/jimmybatuhan/riival/blob/190cc69a0d9ebbde2199efbc57c525186a98ecc7/app/Http/Controllers/LessonController.php#L25)):*
> ```PHP
>         $course = Course::findOrFail($request->course_id);
> 
>         $videoUri = Vimeo::upload($request->video, array(
> ```

use [] instead of array(),  add trailing comma as well
___
*[app/Http/Controllers/LessonController.php, line 29 at r8](https://reviewable.io/reviews/jimmybatuhan/riival/21#-MNpO-ok0JZGCmiOxC1A:-MNpO-ok0JZGCmiOxC1B:bcf5lvs) ([raw file](https://github.com/jimmybatuhan/riival/blob/190cc69a0d9ebbde2199efbc57c525186a98ecc7/app/Http/Controllers/LessonController.php#L29)):*
> ```PHP
>         ));
> 
>         $videoData = Vimeo::request($videoUri, array(), 'GET');
> ```

[] instead of array()
___
*[app/Http/Controllers/LessonController.php, line 42 at r8](https://reviewable.io/reviews/jimmybatuhan/riival/21#-MNpNtJ0BpPN6AuOLYx2:-MNpNtJ0BpPN6AuOLYx3:b3kqv) ([raw file](https://github.com/jimmybatuhan/riival/blob/190cc69a0d9ebbde2199efbc57c525186a98ecc7/app/Http/Controllers/LessonController.php#L42)):*
> ```PHP
>             'description' => $request->description,
>             'duration' => $request->duration,
>             'video_link' => $videoLink
> ```

,
___
*[app/Http/Controllers/LessonController.php, line 81 at r8](https://reviewable.io/reviews/jimmybatuhan/riival/21#-MNpOqGB1ZHYNA_87C02:-MNpOqGB1ZHYNA_87C03:bpsr8xx) ([raw file](https://github.com/jimmybatuhan/riival/blob/190cc69a0d9ebbde2199efbc57c525186a98ecc7/app/Http/Controllers/LessonController.php#L81)):*
> ```PHP
>     }
> 
>     public function show(Lesson $lesson)
> ```

return type
___
*[config/app.php, line 179 at r8](https://reviewable.io/reviews/jimmybatuhan/riival/21#-MNpOIZQDGEXiZSxktxk:-MNpOIZQDGEXiZSxktxl:bmxn3fa) ([raw file](https://github.com/jimmybatuhan/riival/blob/190cc69a0d9ebbde2199efbc57c525186a98ecc7/config/app.php#L179)):*
> ```PHP
> 
>         Spatie\Permission\PermissionServiceProvider::class,
>         Vimeo\Laravel\VimeoServiceProvider::class
> ```

trailing comma

**Comment by dryldionisio** [comment]
___
*[app/Http/Controllers/LessonController.php, line 5 at r8](https://reviewable.io/reviews/jimmybatuhan/riival/21#-MNpOsxWApspChMMn9Hh:-MNpWrn4CfESef7moDrS:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/190cc69a0d9ebbde2199efbc57c525186a98ecc7/app/Http/Controllers/LessonController.php#L5)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

Sort ascending
</blockquote></details>

Done.

**Comment by dryldionisio** [comment]
___
*[app/Http/Controllers/LessonController.php, line 6 at r8](https://reviewable.io/reviews/jimmybatuhan/riival/21#-MNpNhCD4QKo59b9N1ew:-MNpWseH-weohZDEIxbX:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/190cc69a0d9ebbde2199efbc57c525186a98ecc7/app/Http/Controllers/LessonController.php#L6)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

remove empty line
</blockquote></details>

Done.

**Comment by dryldionisio** [comment]
___
*[app/Http/Controllers/LessonController.php, line 25 at r8](https://reviewable.io/reviews/jimmybatuhan/riival/21#-MNpNw7Q44BKs-LKBz0U:-MNpWuAS-0Tu-tnwGfpE:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/190cc69a0d9ebbde2199efbc57c525186a98ecc7/app/Http/Controllers/LessonController.php#L25)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

use [] instead of array(),  add trailing comma as well
</blockquote></details>

Done.

**Comment by dryldionisio** [comment]
___
*[app/Http/Controllers/LessonController.php, line 29 at r8](https://reviewable.io/reviews/jimmybatuhan/riival/21#-MNpO-ok0JZGCmiOxC1A:-MNpWyGl7SSFhFoo7Evr:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/190cc69a0d9ebbde2199efbc57c525186a98ecc7/app/Http/Controllers/LessonController.php#L29)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

[] instead of array()
</blockquote></details>

Done.

**Comment by dryldionisio** [comment]
___
*[app/Http/Controllers/LessonController.php, line 42 at r8](https://reviewable.io/reviews/jimmybatuhan/riival/21#-MNpNtJ0BpPN6AuOLYx2:-MNpWzw3Cp9ZcmZ3FkhE:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/190cc69a0d9ebbde2199efbc57c525186a98ecc7/app/Http/Controllers/LessonController.php#L42)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

,
</blockquote></details>

Done.

**Comment by dryldionisio** [comment]
___
*[app/Http/Controllers/LessonController.php, line 81 at r8](https://reviewable.io/reviews/jimmybatuhan/riival/21#-MNpOqGB1ZHYNA_87C02:-MNpX1CIDIZmYkwp5fYI:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/190cc69a0d9ebbde2199efbc57c525186a98ecc7/app/Http/Controllers/LessonController.php#L81)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

return type
</blockquote></details>

Done.

**Comment by dryldionisio** [comment]
___
*[config/app.php, line 179 at r8](https://reviewable.io/reviews/jimmybatuhan/riival/21#-MNpOIZQDGEXiZSxktxk:-MNpX5v22ZayapD1y5ri:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/190cc69a0d9ebbde2199efbc57c525186a98ecc7/config/app.php#L179)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

trailing comma
</blockquote></details>

Done.

**Review by jimmybatuhan — APPROVED** [review]
> Reviewed 2 of 8 files at r8, 2 of 2 files at r10, 2 of 2 files at r12.
> *[Reviewable](https://reviewable.io/reviews/jimmybatuhan/riival/21)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
