### PR TITLE
added php code sniffer on test

### PR DESCRIPTION
**Pull request by dryldionisio**
This change is [Reviewable](https://reviewable.io/reviews/jimmybatuhan/riival/8)

### CODE REVIEW

**Review by jimmybatuhan — COMMENTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/jimmybatuhan/riival/8)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @dryldionisio and @jimmybatuhan)

___
*[phpcs.xml, line 12 at r1](https://reviewable.io/reviews/jimmybatuhan/riival/8#-MLD2sZn0WE8q8ip1DAy:-MLD2sZn0WE8q8ip1DAz:b-xbpaxv) ([raw file](https://github.com/jimmybatuhan/riival/blob/afb1064f30d74307bd6f38dccb84d3942ec31b85/phpcs.xml#L12)):*
<details><summary><i alt="summary">Quoted 14 lines of code…</i></summary>

> ```
> ?xml version="1.0"?>
> <ruleset  name="PHP_CodeSniffer">
> <description>PHPCS configuration file.</description>
> 
> <file>app</file>
> 
> <exclude-pattern>*/migrations/*</exclude-pattern>
> 
> <arg  value="np"/>
> 
> <rule  ref="PSR12"/>
> </ruleset>
> ```
</details>


use this ruleset instead

`<?xml version="1.0"?>
<ruleset name="PSR Coding Standard">
    <description>The PSR coding standard.</description>
    <rule ref="PSR1"/>
    <rule ref="PSR2"/>
    <rule ref="PSR12"/>
    <file>app/</file>
    <processes>5</processes>
    <tabWidth>4</tabWidth>
    <exclude>Generic.Files.LineEndings</exclude>
    <exclude-pattern>vendor</exclude-pattern>
    <exclude-pattern>resources</exclude-pattern>
    <exclude-pattern>database/</exclude-pattern>
    <exclude-pattern>storage/</exclude-pattern>
    <exclude-pattern>node_modules/</exclude-pattern>
</ruleset>
`

**Review by jimmybatuhan — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/jimmybatuhan/riival/8)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dryldionisio** [comment]
fix issues on coding standards as well

**Review by jimmybatuhan — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/jimmybatuhan/riival/8#-:-MLGb5zP7kkbNTQazbEE:bnfp4nl)* status: 3 of 14 files reviewed, all discussions resolved (waiting on @jimmybatuhan)

**Review by jimmybatuhan — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/jimmybatuhan/riival/8)* status: 3 of 14 files reviewed, all discussions resolved (waiting on @jimmybatuhan)

**Review by jimmybatuhan — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/jimmybatuhan/riival/8)* status: 3 of 14 files reviewed, all discussions resolved (waiting on @jimmybatuhan)

**Review by jimmybatuhan — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/jimmybatuhan/riival/8#-:-MLGbS3Y3fp5F_JgVdMa:bnfp4nl)* status: 3 of 14 files reviewed, all discussions resolved (waiting on @jimmybatuhan)

**Review by jimmybatuhan — APPROVED** [review]
> Reviewed 11 of 11 files at r8.
> *[Reviewable](https://reviewable.io/reviews/jimmybatuhan/riival/8)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
