### PR TITLE
Feature/login ui update

### PR DESCRIPTION
**Pull request by jimmybatuhan**
This change is [Reviewable](https://reviewable.io/reviews/jimmybatuhan/riival/16)

### CODE REVIEW

**Comment by dryldionisio** [comment]
:lgtm:

**Review by dryldionisio — APPROVED** [review]
> Reviewed 6 of 6 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/jimmybatuhan/riival/16)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by jimmybatuhan — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/jimmybatuhan/riival/16#-:-MM9bmgZ6KiMmDISvSAN:bnfp4nl)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @dryldionisio)

**Review by dryldionisio — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/jimmybatuhan/riival/16)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
