### PR TITLE
Updates the video status in background

### PR DESCRIPTION
**Pull request by jimmybatuhan**
This change is [Reviewable](https://reviewable.io/reviews/jimmybatuhan/riival/26)

### CODE REVIEW

**Comment by dryldionisio** [comment]
:lgtm:

**Review by dryldionisio — DISMISSED** [review]
> Reviewed 4 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/jimmybatuhan/riival/26)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by jimmybatuhan — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/jimmybatuhan/riival/26#-:-MNsal-vBMGRy70vV85u:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dryldionisio — DISMISSED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/jimmybatuhan/riival/26)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dryldionisio** [comment]
:lgtm:

**Review by dryldionisio — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/jimmybatuhan/riival/26)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
