### PR TITLE
added field for video id and mutators for the lesson request

### PR DESCRIPTION
**Pull request by dryldionisio**
This change is [Reviewable](https://reviewable.io/reviews/jimmybatuhan/riival/24)

### CODE REVIEW

**Review by jimmybatuhan — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/jimmybatuhan/riival/24)* status: all files reviewed, 6 unresolved discussions (waiting on @dryldionisio)

___
*[.env.example, line 51 at r3](https://reviewable.io/reviews/jimmybatuhan/riival/24#-MNr-ds5-QjXtMrEgcaN:-MNr-ds61heDqU9_pswL:bcjafz6) ([raw file](https://github.com/jimmybatuhan/riival/blob/ab3de30d4099f5ae5ad52e6443b79029b42a07ee/.env.example#L51)):*
> ```
> https://player.vimeo.com/video
> ```
remove
___
*[app/Http/Controllers/LessonController.php, line 39 at r3](https://reviewable.io/reviews/jimmybatuhan/riival/24#-MNr-kZP0zAhdgxkjb-Y:-MNr-kZP0zAhdgxkjb-Z:b8xmy70) ([raw file](https://github.com/jimmybatuhan/riival/blob/ab3de30d4099f5ae5ad52e6443b79029b42a07ee/app/Http/Controllers/LessonController.php#L39)):*
> ```
>  'video_link' => "",
> ```
remove
___
*[database/factories/LessonFactory.php, line 15 at r3](https://reviewable.io/reviews/jimmybatuhan/riival/24#-MNr0MGk1zSVN9_cO_Gr:-MNr0MGk1zSVN9_cO_Gs:basn1k5) ([raw file](https://github.com/jimmybatuhan/riival/blob/ab3de30d4099f5ae5ad52e6443b79029b42a07ee/database/factories/LessonFactory.php#L15)):*
> ```
>  'video_link' => $faker->url,
> ```
remove
___
*[database/migrations/2020_12_06_022145_add_video_id_on_lessons.php, line 16 at r3](https://reviewable.io/reviews/jimmybatuhan/riival/24#-MNr1WFSDHT-rceI-RLA:-MNr1WFSDHT-rceI-RLB:bh3o6fy) ([raw file](https://github.com/jimmybatuhan/riival/blob/ab3de30d4099f5ae5ad52e6443b79029b42a07ee/database/migrations/2020_12_06_022145_add_video_id_on_lessons.php#L16)):*
> ```PHP
>     public function up()
>     {
> ```

remove empty line
___
*[database/migrations/2020_12_06_022145_add_video_id_on_lessons.php, line 18 at r3](https://reviewable.io/reviews/jimmybatuhan/riival/24#-MNr0V4LD7S9heF5rBmV:-MNr0V4LD7S9heF5rBmW:blyqw21) ([raw file](https://github.com/jimmybatuhan/riival/blob/ab3de30d4099f5ae5ad52e6443b79029b42a07ee/database/migrations/2020_12_06_022145_add_video_id_on_lessons.php#L18)):*
> ```
>  $table->dropColumn('duration');
> ```

you can include this in the schema above or better yet just update the existing column

`$table->integer('duration')->nullable()->change()`
___
*[database/migrations/2020_12_06_022145_add_video_id_on_lessons.php, line 39 at r3](https://reviewable.io/reviews/jimmybatuhan/riival/24#-MNr0m2SAsEnM7uTQs5u:-MNr0m2SAsEnM7uTQs5v:b-ugsfho) ([raw file](https://github.com/jimmybatuhan/riival/blob/ab3de30d4099f5ae5ad52e6443b79029b42a07ee/database/migrations/2020_12_06_022145_add_video_id_on_lessons.php#L39)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>         Schema::table('lessons', function (Blueprint $table) {
>             $table->dropColumn('video_id');
>             $table->dropColumn('duration');
>         });
>         Schema::table('lessons', function (Blueprint $table) {
>             $table->string('duration')->after('video_link');
>         });
> ```
</details>

use one `Schema`

**Review by jimmybatuhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/jimmybatuhan/riival/24)* status: all files reviewed, 7 unresolved discussions (waiting on @dryldionisio)

___
*[database/migrations/2020_12_06_022145_add_video_id_on_lessons.php, line 34 at r3](https://reviewable.io/reviews/jimmybatuhan/riival/24#-MNr1znbBUYAU4U_j0iu:-MNr1znc83jFbpyDhEY9:bh3o6fy) ([raw file](https://github.com/jimmybatuhan/riival/blob/ab3de30d4099f5ae5ad52e6443b79029b42a07ee/database/migrations/2020_12_06_022145_add_video_id_on_lessons.php#L34)):*
> ```PHP
>     public function down()
>     {
> ```

remove empty line

**Review by jimmybatuhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/jimmybatuhan/riival/24)* status: all files reviewed, 8 unresolved discussions (waiting on @dryldionisio)

___
*[app/Models/Lesson.php, line 17 at r3](https://reviewable.io/reviews/jimmybatuhan/riival/24#-MNr2lXk16fjR56wH2RI:-MNr2lXl-OnoQesQ931t:b-t7pav5) ([raw file](https://github.com/jimmybatuhan/riival/blob/ab3de30d4099f5ae5ad52e6443b79029b42a07ee/app/Models/Lesson.php#L17)):*
> ```
>  ['video_duration'];
> ```
append video link as well

**Review by jimmybatuhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/jimmybatuhan/riival/24)* status: all files reviewed, 9 unresolved discussions (waiting on @dryldionisio)

___
*[database/migrations/2020_12_06_022145_add_video_id_on_lessons.php, line 23 at r3](https://reviewable.io/reviews/jimmybatuhan/riival/24#-MNr3gabDgzCdebydDDq:-MNr3gabDgzCdebydDDr:b-5bfsq) ([raw file](https://github.com/jimmybatuhan/riival/blob/ab3de30d4099f5ae5ad52e6443b79029b42a07ee/database/migrations/2020_12_06_022145_add_video_id_on_lessons.php#L23)):*
> ```
>             $table->string('video_id')->after('description')->nullable();
>             $table->integer('duration')->after('video_link')->nullable();
> ```
remove nullable

**Review by jimmybatuhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/jimmybatuhan/riival/24)* status: all files reviewed, 10 unresolved discussions (waiting on @dryldionisio)

___
*[database/migrations/2020_12_06_022145_add_video_id_on_lessons.php, line 22 at r3](https://reviewable.io/reviews/jimmybatuhan/riival/24#-MNr3lU98WrJR_ZvVNiZ:-MNr3lU98WrJR_ZvVNi_:b7n5xxf) ([raw file](https://github.com/jimmybatuhan/riival/blob/ab3de30d4099f5ae5ad52e6443b79029b42a07ee/database/migrations/2020_12_06_022145_add_video_id_on_lessons.php#L22)):*
> ```
>  $table->string('video_id')->after('description')->nullable();
> ```
integer

**Comment by dryldionisio** [comment]
___
*[.env.example, line 51 at r3](https://reviewable.io/reviews/jimmybatuhan/riival/24#-MNr-ds5-QjXtMrEgcaN:-MNrNbtXATba1HCl7LBg:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/ab3de30d4099f5ae5ad52e6443b79029b42a07ee/.env.example#L51)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

> ```
> https://player.vimeo.com/video
> ```
remove
</blockquote></details>

Done.

**Comment by dryldionisio** [comment]
___
*[app/Http/Controllers/LessonController.php, line 39 at r3](https://reviewable.io/reviews/jimmybatuhan/riival/24#-MNr-kZP0zAhdgxkjb-Y:-MNrNd_GBu94dyJa70E6:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/ab3de30d4099f5ae5ad52e6443b79029b42a07ee/app/Http/Controllers/LessonController.php#L39)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

> ```
>  'video_link' => "",
> ```
remove
</blockquote></details>

Done.

**Comment by dryldionisio** [comment]
___
*[app/Models/Lesson.php, line 17 at r3](https://reviewable.io/reviews/jimmybatuhan/riival/24#-MNr2lXk16fjR56wH2RI:-MNrNh0zC_I2CkekOECt:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/ab3de30d4099f5ae5ad52e6443b79029b42a07ee/app/Models/Lesson.php#L17)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

> ```
>  ['video_duration'];
> ```
append video link as well
</blockquote></details>

Done.

**Comment by dryldionisio** [comment]
___
*[database/factories/LessonFactory.php, line 15 at r3](https://reviewable.io/reviews/jimmybatuhan/riival/24#-MNr0MGk1zSVN9_cO_Gr:-MNrNjeK9Er1ZnacueZS:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/ab3de30d4099f5ae5ad52e6443b79029b42a07ee/database/factories/LessonFactory.php#L15)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

> ```
>  'video_link' => $faker->url,
> ```
remove
</blockquote></details>

Done.

**Comment by dryldionisio** [comment]
___
*[database/migrations/2020_12_06_022145_add_video_id_on_lessons.php, line 16 at r3](https://reviewable.io/reviews/jimmybatuhan/riival/24#-MNr1WFSDHT-rceI-RLA:-MNrNlQf7Msm-eVFRO92:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/ab3de30d4099f5ae5ad52e6443b79029b42a07ee/database/migrations/2020_12_06_022145_add_video_id_on_lessons.php#L16)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

remove empty line
</blockquote></details>

Done.

**Comment by dryldionisio** [comment]
___
*[database/migrations/2020_12_06_022145_add_video_id_on_lessons.php, line 18 at r3](https://reviewable.io/reviews/jimmybatuhan/riival/24#-MNr0V4LD7S9heF5rBmV:-MNrNpK10kPw5nz7hhEF:bl7phtx) ([raw file](https://github.com/jimmybatuhan/riival/blob/ab3de30d4099f5ae5ad52e6443b79029b42a07ee/database/migrations/2020_12_06_022145_add_video_id_on_lessons.php#L18)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

> ```
>  $table->dropColumn('duration');
> ```

you can include this in the schema above or better yet just update the existing column

`$table->integer('duration')->nullable()->change()`
</blockquote></details>

Done. Need to drop and insert first on separate schemas

**Comment by dryldionisio** [comment]
___
*[database/migrations/2020_12_06_022145_add_video_id_on_lessons.php, line 22 at r3](https://reviewable.io/reviews/jimmybatuhan/riival/24#-MNr3lU98WrJR_ZvVNiZ:-MNrOpOr7LZya-fEXLr3:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/ab3de30d4099f5ae5ad52e6443b79029b42a07ee/database/migrations/2020_12_06_022145_add_video_id_on_lessons.php#L22)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

> ```
>  $table->string('video_id')->after('description')->nullable();
> ```
integer
</blockquote></details>

Done.

**Comment by dryldionisio** [comment]
___
*[database/migrations/2020_12_06_022145_add_video_id_on_lessons.php, line 23 at r3](https://reviewable.io/reviews/jimmybatuhan/riival/24#-MNr3gabDgzCdebydDDq:-MNrOrHM4__HQ30UyNrn:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/ab3de30d4099f5ae5ad52e6443b79029b42a07ee/database/migrations/2020_12_06_022145_add_video_id_on_lessons.php#L23)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

> ```
>             $table->string('video_id')->after('description')->nullable();
>             $table->integer('duration')->after('video_link')->nullable();
> ```
remove nullable
</blockquote></details>

Done.

**Comment by dryldionisio** [comment]
___
*[database/migrations/2020_12_06_022145_add_video_id_on_lessons.php, line 34 at r3](https://reviewable.io/reviews/jimmybatuhan/riival/24#-MNr1znbBUYAU4U_j0iu:-MNrOsoB4675QQcYayBW:b-896fix) ([raw file](https://github.com/jimmybatuhan/riival/blob/ab3de30d4099f5ae5ad52e6443b79029b42a07ee/database/migrations/2020_12_06_022145_add_video_id_on_lessons.php#L34)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

remove empty line
</blockquote></details>

Done.

**Comment by dryldionisio** [comment]
___
*[database/migrations/2020_12_06_022145_add_video_id_on_lessons.php, line 39 at r3](https://reviewable.io/reviews/jimmybatuhan/riival/24#-MNr0m2SAsEnM7uTQs5u:-MNrOw3Z0ayrflD4JKv9:b-96k7bl) ([raw file](https://github.com/jimmybatuhan/riival/blob/ab3de30d4099f5ae5ad52e6443b79029b42a07ee/database/migrations/2020_12_06_022145_add_video_id_on_lessons.php#L39)):*
<details><summary><i>Previously, jimmybatuhan (plumeray) wrote…</i></summary><blockquote>

> ```
>         Schema::table('lessons', function (Blueprint $table) {
>             $table->dropColumn('video_id');
>             $table->dropColumn('duration');
>         });
>         Schema::table('lessons', function (Blueprint $table) {
>             $table->string('duration')->after('video_link');
>         });
> ```
use one `Schema`
</blockquote></details>

Done. Need to be on separate schema as migration fails

**Review by jimmybatuhan — APPROVED** [review]
> Reviewed 3 of 3 files at r4, 4 of 4 files at r5, 1 of 1 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/jimmybatuhan/riival/24)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dryldionisio** [comment]
:lgtm:

**Pull request merged**
